#https://hub.docker.com/r/lambdalinux/baseimage-amzn/tags/
FROM lambdalinux/baseimage-amzn:2017.03-003

RUN yum -y install gcc libffi-devel openssl-devel python27-devel python27-pip && \
    pip install --upgrade pip && pip install ansible=={{ test_ansible_version }}

ADD . /tmp

WORKDIR /tmp


